if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);
settings.outformat = "pdf";
settings.render = 0;
settings.prc = false;
import olympiad;
import cse5;
size(8cm);
import olympiad;
import cse5;
size(5cm);
real w=2.2;
pair O,I,J;
O=(0,0);I=(1,0);J=(0,1);
path bsqb = O--I;
path bsqr = I--I+J;
path bsqt = I+J--J;
path bsql = J--O;
path lsqb = shift((1.2,0.75))*scale(0.5)*bsqb;
path lsqr = shift((1.2,0.75))*scale(0.5)*bsqr;
path lsqt = shift((1.2,0.75))*scale(0.5)*bsqt;
path lsql = shift((1.2,0.75))*scale(0.5)*bsql;
draw(bsqb,dashed);
draw(bsqr,dashed);
draw(bsqt,dashed);
draw(bsql,dashed);
draw(lsqb,dashed);
draw(lsqr,dashed);
draw(lsqt,dashed);
draw(lsql,dashed);
label(scale(3)*"$\times$",(w,1/3));
draw(shift(1.3w,0)*bsqb,dashed);
draw(shift(1.3w,0)*bsqr,dashed);
draw(shift(1.3w,0)*bsqt,dashed);
draw(shift(1.3w,0)*bsql,dashed);
draw(shift(1.3w,0)*lsqb,dashed);
draw(shift(1.3w,0)*lsqr,dashed);
draw(shift(1.3w,0)*lsqt,dashed);
draw(shift(1.3w,0)*lsql,dashed);