if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);
settings.outformat = "pdf";
settings.render = 0;
settings.prc = false;
import olympiad;
import cse5;
size(8cm);
filldraw((-1,-1)--(-1,1)--(1,1)--(1,-1)--cycle,gray,black);
filldraw(Circle((0,0),1), mediumgray,black);
filldraw((-1,0)--(0,1)--(1,0)--(0,-1)--cycle,white,black);