if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);
settings.outformat = "pdf";
settings.render = 0;
settings.prc = false;
import olympiad;
import cse5;
size(8cm);
import olympiad;
import cse5;
fill((0.5, 4.5)--(1.5,4.5)--(1.5,2.5)--(0.5,2.5)--cycle,lightgray);
fill((1.5,3.5)--(2.5,3.5)--(2.5,1.5)--(1.5,1.5)--cycle,lightgray);
label("$8$", (1, 0));
label("$C$", (2, 0));
label("$8$", (3, 0));
label("$8$", (0, 1));
label("$C$", (1, 1));
label("$M$", (2, 1));
label("$C$", (3, 1));
label("$8$", (4, 1));
label("$C$", (0, 2));
label("$M$", (1, 2));
label("$A$", (2, 2));
label("$M$", (3, 2));
label("$C$", (4, 2));
label("$8$", (0, 3));
label("$C$", (1, 3));
label("$M$", (2, 3));
label("$C$", (3, 3));
label("$8$", (4, 3));
label("$8$", (1, 4));
label("$C$", (2, 4));
label("$8$", (3, 4));