if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);
settings.outformat = "pdf";
settings.render = 0;
settings.prc = false;
import olympiad;
import cse5;
size(8cm);
import olympiad;
import cse5;
import geometry;
size(10cm);
point O1=(0,0),O2=(15,0),B=9*dir(30);
circle w1=circle(O1,9),w2=circle(O2,6),o=circle(O1,O2,B);
point A=intersectionpoints(o,w2)[1],D=intersectionpoints(o,w2)[0],C=intersectionpoints(o,w1)[0];
filldraw(A--B--O1--C--D--O2--cycle,0.2*red+white,black);
draw(w1);
draw(w2);
draw(O1--O2,dashed);
draw(o);
dot(O1);
dot(O2);
dot(A);
dot(D);
dot(C);
dot(B);
label("$\omega_1$",8*dir(110),SW);
label("$\omega_2$",5*dir(70)+(15,0),SE);
label("$O_1$",O1,W);
label("$O_2$",O2,E);
label("$B$",B,N+1/2*E);
label("$A$",A,N+1/2*W);
label("$C$",C,S+1/4*W);
label("$D$",D,S+1/4*E);
label("$15$",midpoint(O1--O2),N);
label("$16$",midpoint(C--D),N);
label("$2$",midpoint(A--B),S);
label("$\Omega$",o.C+(o.r-1)*dir(270));