if(!settings.multipleView) settings.batchView=false;
settings.tex="pdflatex";
if(settings.render < 0) settings.render=4;
settings.outformat="";
settings.inlineimage=true;
settings.embed=true;
settings.toolbar=false;
viewportmargin=(2,2);
settings.outformat = "pdf";
settings.render = 0;
settings.prc = false;
import olympiad;
import cse5;
size(8cm);
import olympiad;
import cse5;
unitsize(6);
pair P = (0, 0), Q = (0, 23), R = (27, 23), SS = (27, 0);
pair A = (0, 6), B = (8, 0), C = (19, 0), D = (27, 6), EE = (27, 17), F = (19, 23), G = (8, 23), J = (0, 23/2), H = (0, 17);
draw(P--Q--R--SS--cycle);
draw(J--B);
draw(J--C);
draw(J--D);
draw(J--EE);
draw(J--F);
draw(J--G);
draw(A--B);
draw(H--G);
real dark = 0.6;
filldraw(A--B--P--cycle, gray(dark));
filldraw(H--G--Q--cycle, gray(dark));
filldraw(F--EE--R--cycle, gray(dark));
filldraw(D--C--SS--cycle, gray(dark));
dot(A);
dot(B);
dot(C);
dot(D);
dot(EE);
dot(F);
dot(G);
dot(H);
dot(J);
dot(H);
defaultpen(fontsize(10pt));
real r = 1.3;
label("$A$", A, W*r);
label("$B$", B, S*r);
label("$C$", C, S*r);
label("$D$", D, E*r);
label("$E$", EE, E*r);
label("$F$", F, N*r);
label("$G$", G, N*r);
label("$H$", H, W*r);
label("$J$", J, W*r);